services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: ghcr.io/bdilhof/app-manna:1.0.0
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
    volumes:
      - .:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
