services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
    volumes:
      - .:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    ports:
      - "3306:3306"
