version: "3.9"

services:
  app:
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    ports:
      - "3306:3306"
